### ISSUE TITLE
Hardcoded constants

### ISSUE THREAD

**Issue by pgampe** [typo3-themes/theme_bootstrap_slate#3]
the them includes hardcoded constants to resources: `http://127.0.1.1/typo3-6.2-dist/` please use relative paths for this.

**Comment by pgampe** [comment]
```
themes.configuration.baseurl = 
themes.configuration.baseurlIcon = typo3conf/ext/theme_bootstrap/Resources/Public/Icons/
themes.configuration.baseurlImage = typo3conf/ext/theme_bootstrap/Resources/Public/Images/
```

works for me

**Comment by kaystrobach** [comment]
could you please create a merge request, will then check it and add it to the official release

thanks a lot

**Comment by pgampe** [comment]
afk this is part of the t3d export, at least it is in the db after install

**Comment by kaystrobach** [comment]
have you used the distribution or the vagrant box?

**Comment by pgampe** [comment]
just the distribution in my local 6.2-dev install

**Comment by kaystrobach** [comment]
have you used:
- http://typo3.org/extensions/repository/view/themes_distribution

or 
- https://github.com/typo3-themes/Vagrant.Themes

for installation / setup?

**Comment by pgampe** [comment]
Themes_distribution from TER on a 6.2-dev install.

**Comment by kaystrobach** [comment]
ok, then i have an idea where to fix it ;)

**Comment by kaystrobach** [comment]
@tdeuling maybe you can take a look into the distribution?
